// import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/global.scss";

// export const metadata: Metadata = {
//   title: "Prostoretail - магазин электроники",
//   description: "Generated by create next app",
// };

const geistRoboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${geistRoboto.variable} antialiased`}>{children}</body>
    </html>
  );
}
